"""Precomputed stand-ins for the imaging tools, for the public demo.

These import no torch. They read results that scripts/precompute_demo.py
generated by running the real models, and they are byte-identical to what the
real tools returned for those cases.

EVERY result carries `precomputed: True` and a note saying so. That is not
decoration. "This model runs on your image in 40 ms" and "I ran this model last
Tuesday on 40 images" are different claims, and a demo that blurs them is
misrepresenting the system. A case that is not in the cache returns a clear
error rather than falling back to anything.
"""

from __future__ import annotations

import base64
import json
from functools import lru_cache
from pathlib import Path

from radreport.config import DATA_DIR
from radreport.tools.errors import ToolError

CACHE_PATH = DATA_DIR / "demo_cache.json"
NOTE = ("Precomputed result: the model was run offline on this fixed case set, "
        "not on live input. See scripts/precompute_demo.py.")


@lru_cache(maxsize=1)
def _cache() -> dict:
    if not CACHE_PATH.exists():
        raise ToolError(
            f"Demo cache not found at {CACHE_PATH}. Run "
            "`python scripts/precompute_demo.py` or unset RADREPORT_DEMO.",
            tool="demo", recoverable=False,
        )
    return json.loads(CACHE_PATH.read_text())


def available_cases() -> list[str]:
    try:
        return sorted(_cache())
    except ToolError:
        return []


def _normalise(image_path: str | Path) -> str:
    """Accept a path, a filename or a bare case id, as the real tools do."""
    stem = Path(str(image_path)).name
    for suffix in (".dcm.png", ".png", ".dcm"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    return stem


def _entry(image_path: str | Path) -> dict:
    case_id = _normalise(image_path)
    cache = _cache()
    if case_id not in cache:
        raise ToolError(
            f"{case_id!r} is not in the precomputed demo set. This deployment "
            f"serves {len(cache)} fixed cases and cannot run the models on new "
            "images. Pick one of the listed cases, or run locally.",
            tool="demo", recoverable=False,
        )
    return cache[case_id]


def classify_xray(image_path: str | Path, threshold: float = 0.5) -> dict:
    entry = _entry(image_path)
    if "classify" not in entry:
        raise ToolError(entry.get("classify_error", "no cached classification"), tool="classify_xray")
    result = dict(entry["classify"])
    # Re-apply the threshold so the argument still means something.
    result["threshold"] = threshold
    result["above_threshold"] = {k: v for k, v in result["findings"].items() if v >= threshold}
    result["precomputed"] = True
    result["note"] = NOTE
    return result


def segment_lungs(image_path: str | Path, prob_threshold: float = 0.5) -> dict:
    entry = _entry(image_path)
    if "segment" not in entry:
        raise ToolError(entry.get("segment_error", "no cached segmentation"), tool="segment_lungs")
    return {**entry["segment"], "precomputed": True, "note": NOTE}


def compute_ctr(mask_handle: str) -> dict:
    """Takes the demo:// handle that segment_lungs returned."""
    case_id = str(mask_handle).replace("demo://", "")
    entry = _entry(case_id)
    if "ctr" not in entry:
        raise ToolError("no cached CTR for this case", tool="compute_ctr")
    return {**entry["ctr"], "precomputed": True, "note": NOTE}


def image_bytes(case_id: str, overlay: bool = False) -> bytes | None:
    entry = _entry(case_id)
    b64 = entry.get("overlay_b64" if overlay else "image_b64")
    return base64.b64decode(b64) if b64 else None
